// Code generated by Iacker. DO NOT EDIT IT.
package v1

import (
	_ "embed"
)

// ResourceType is the unique type name of Monitor
const ResourceType = "Monitor"

//go:embed monitor.schema.json
var schemaRaw []byte

// resourceSchema is the schema of Monitor
type resourceSchema struct{}

// Raw returns the raw schema bytes of Monitor
func (s *resourceSchema) Raw() []byte {
	return schemaRaw
}

// ReferenceTypes returns the related resource types of Monitor
func (s *resourceSchema) ReferenceTypes() []string {
	return []string{
		"AlertPolicy",
		"Dashboard",
	}
}
