// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/monitor/v1/monitor.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AlertPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AlertPolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AlertPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AlertPolicyMultiError, or
// nil if none found.
func (m *AlertPolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *AlertPolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Id != nil {
		// no validation rules for Id
	}

	if len(errors) > 0 {
		return AlertPolicyMultiError(errors)
	}

	return nil
}

// AlertPolicyMultiError is an error wrapping multiple validation errors
// returned by AlertPolicy.ValidateAll() if the designated constraints aren't met.
type AlertPolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AlertPolicyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AlertPolicyMultiError) AllErrors() []error { return m }

// AlertPolicyValidationError is the validation error returned by
// AlertPolicy.Validate if the designated constraints aren't met.
type AlertPolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AlertPolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AlertPolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AlertPolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AlertPolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AlertPolicyValidationError) ErrorName() string { return "AlertPolicyValidationError" }

// Error satisfies the builtin error interface
func (e AlertPolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAlertPolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AlertPolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AlertPolicyValidationError{}

// Validate checks the field values on Dashboard with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Dashboard) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Dashboard with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DashboardMultiError, or nil
// if none found.
func (m *Dashboard) ValidateAll() error {
	return m.validate(true)
}

func (m *Dashboard) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Id != nil {
		// no validation rules for Id
	}

	if len(errors) > 0 {
		return DashboardMultiError(errors)
	}

	return nil
}

// DashboardMultiError is an error wrapping multiple validation errors returned
// by Dashboard.ValidateAll() if the designated constraints aren't met.
type DashboardMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DashboardMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DashboardMultiError) AllErrors() []error { return m }

// DashboardValidationError is the validation error returned by
// Dashboard.Validate if the designated constraints aren't met.
type DashboardValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DashboardValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DashboardValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DashboardValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DashboardValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DashboardValidationError) ErrorName() string { return "DashboardValidationError" }

// Error satisfies the builtin error interface
func (e DashboardValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDashboard.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DashboardValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DashboardValidationError{}

// Validate checks the field values on Monitor with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Monitor) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Monitor with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MonitorMultiError, or nil if none found.
func (m *Monitor) ValidateAll() error {
	return m.validate(true)
}

func (m *Monitor) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Manifest

	if all {
		switch v := interface{}(m.GetAlertPolicy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MonitorValidationError{
					field:  "AlertPolicy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MonitorValidationError{
					field:  "AlertPolicy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAlertPolicy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MonitorValidationError{
				field:  "AlertPolicy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDashboard()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MonitorValidationError{
					field:  "Dashboard",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MonitorValidationError{
					field:  "Dashboard",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDashboard()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MonitorValidationError{
				field:  "Dashboard",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MonitorMultiError(errors)
	}

	return nil
}

// MonitorMultiError is an error wrapping multiple validation errors returned
// by Monitor.ValidateAll() if the designated constraints aren't met.
type MonitorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MonitorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MonitorMultiError) AllErrors() []error { return m }

// MonitorValidationError is the validation error returned by Monitor.Validate
// if the designated constraints aren't met.
type MonitorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MonitorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MonitorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MonitorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MonitorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MonitorValidationError) ErrorName() string { return "MonitorValidationError" }

// Error satisfies the builtin error interface
func (e MonitorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMonitor.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MonitorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MonitorValidationError{}
