// Code generated by Iacker. DO NOT EDIT IT.
package v1

import (
	_ "embed"
)

// ResourceType is the unique type name of Mute
const ResourceType = "Mute"

//go:embed mute.schema.json
var schemaRaw []byte

const (
	// MuteRangeTypeMonitor is the value of Monitor
	MuteRangeTypeMonitor = "monitor"
	// MuteRangeTypeAlertPolicy is the value of Alert Policy
	MuteRangeTypeAlertPolicy = "alert_policy"
)

const (
	// NotifyTargetTypeMemberGroup is the value of MemberGroup
	NotifyTargetTypeMemberGroup = "member_group"
	// NotifyTargetTypeNotification is the value of Notification
	NotifyTargetTypeNotification = "notification"
)

// resourceSchema is the schema of Mute
type resourceSchema struct{}

// Raw returns the raw schema bytes of Mute
func (s *resourceSchema) Raw() []byte {
	return schemaRaw
}

// ReferenceTypes returns the related resource types of Mute
func (s *resourceSchema) ReferenceTypes() []string {
	return []string{}
}
