// Code generated by Iacker. DO NOT EDIT IT.
package v1

import (
	_ "embed"
)

// ResourceType is the unique type name of Member
const ResourceType = "Member"

//go:embed member.schema.json
var schemaRaw []byte

const (
	// MemberRoleOwner is the value of Owner
	MemberRoleOwner = "owner"
	// MemberRoleAdministrator is the value of Administrator
	MemberRoleAdministrator = "wsAdmin"
	// MemberRoleStandard is the value of Standard
	MemberRoleStandard = "general"
	// MemberRoleReadOnly is the value of Read-only
	MemberRoleReadOnly = "readOnly"
)

// resourceSchema is the schema of Member
type resourceSchema struct{}

// Raw returns the raw schema bytes of Member
func (s *resourceSchema) Raw() []byte {
	return schemaRaw
}

// ReferenceTypes returns the related resource types of Member
func (s *resourceSchema) ReferenceTypes() []string {
	return []string{}
}
