// Code generated by Iacker. DO NOT EDIT IT.
package v1

import (
	_ "embed"
)

// ResourceType is the unique type name of AlertPolicy
const ResourceType = "AlertPolicy"

//go:embed alertpolicy.schema.json
var schemaRaw []byte

const (
	// AlertPolicyStatusesAll is the value of ALL
	AlertPolicyStatusesAll = "ALL"
	// AlertPolicyStatusesCritical is the value of critical
	AlertPolicyStatusesCritical = "critical"
	// AlertPolicyStatusesError is the value of error
	AlertPolicyStatusesError = "error"
	// AlertPolicyStatusesWarning is the value of warning
	AlertPolicyStatusesWarning = "warning"
	// AlertPolicyStatusesInfo is the value of info
	AlertPolicyStatusesInfo = "info"
	// AlertPolicyStatusesOk is the value of ok
	AlertPolicyStatusesOk = "ok"
	// AlertPolicyStatusesNodata is the value of nodata
	AlertPolicyStatusesNodata = "nodata"
	// AlertPolicyStatusesNodataOk is the value of nodata_ok
	AlertPolicyStatusesNodataOk = "nodata_ok"
	// AlertPolicyStatusesNodataAsOk is the value of nodata_as_ok
	AlertPolicyStatusesNodataAsOk = "nodata_as_ok"
)

const (
	// AlertTargetTypeMembergroup is the value of Member group
	AlertTargetTypeMembergroup = "member_group"
	// AlertTargetTypeNotification is the value of Notification object
	AlertTargetTypeNotification = "notification"
)

// resourceSchema is the schema of AlertPolicy
type resourceSchema struct{}

// Raw returns the raw schema bytes of AlertPolicy
func (s *resourceSchema) Raw() []byte {
	return schemaRaw
}

// ReferenceTypes returns the related resource types of AlertPolicy
func (s *resourceSchema) ReferenceTypes() []string {
	return []string{
		"MemberGroup",
		"Notification",
	}
}
