// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pkg/resources/alertpolicy/v1/alertpolicy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Alert Policy Name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Silent timeout timestamp
	SilentTimeout *string `protobuf:"bytes,2,opt,name=silent_timeout,json=silentTimeout,proto3,oneof" json:"silent_timeout,omitempty"`
	// The status value of the event to be sent
	Statuses []string `protobuf:"bytes,3,rep,name=statuses,proto3" json:"statuses,omitempty"`
	// Alert Action
	AlertTargets []*AlertTarget `protobuf:"bytes,4,rep,name=alert_targets,json=alertTargets,proto3" json:"alert_targets,omitempty"`
}

func (x *AlertPolicy) Reset() {
	*x = AlertPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertPolicy) ProtoMessage() {}

func (x *AlertPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertPolicy.ProtoReflect.Descriptor instead.
func (*AlertPolicy) Descriptor() ([]byte, []int) {
	return file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescGZIP(), []int{0}
}

func (x *AlertPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertPolicy) GetSilentTimeout() string {
	if x != nil && x.SilentTimeout != nil {
		return *x.SilentTimeout
	}
	return ""
}

func (x *AlertPolicy) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *AlertPolicy) GetAlertTargets() []*AlertTarget {
	if x != nil {
		return x.AlertTargets
	}
	return nil
}

type AlertTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Alert type
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Notification
	Notification *TargetNotification `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	// Member Group
	MemberGroup *TargetMemberGroup `protobuf:"bytes,3,opt,name=member_group,json=memberGroup,proto3" json:"member_group,omitempty"`
}

func (x *AlertTarget) Reset() {
	*x = AlertTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertTarget) ProtoMessage() {}

func (x *AlertTarget) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertTarget.ProtoReflect.Descriptor instead.
func (*AlertTarget) Descriptor() ([]byte, []int) {
	return file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescGZIP(), []int{1}
}

func (x *AlertTarget) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlertTarget) GetNotification() *TargetNotification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *AlertTarget) GetMemberGroup() *TargetMemberGroup {
	if x != nil {
		return x.MemberGroup
	}
	return nil
}

type TargetMemberGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Member Group
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TargetMemberGroup) Reset() {
	*x = TargetMemberGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetMemberGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetMemberGroup) ProtoMessage() {}

func (x *TargetMemberGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetMemberGroup.ProtoReflect.Descriptor instead.
func (*TargetMemberGroup) Descriptor() ([]byte, []int) {
	return file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescGZIP(), []int{2}
}

func (x *TargetMemberGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TargetNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Notification
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TargetNotification) Reset() {
	*x = TargetNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetNotification) ProtoMessage() {}

func (x *TargetNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetNotification.ProtoReflect.Descriptor instead.
func (*TargetNotification) Descriptor() ([]byte, []int) {
	return file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescGZIP(), []int{3}
}

func (x *TargetNotification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_pkg_resources_alertpolicy_v1_alertpolicy_proto protoreflect.FileDescriptor

var file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1c, 0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0xcc,
	0x01, 0x0a, 0x0b, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x0e, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x69,
	0x6c, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12, 0x4e, 0x0a, 0x0d, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x0c, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x73,
	0x69, 0x6c, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0xcb, 0x01,
	0x0a, 0x0b, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x54, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x23, 0x0a, 0x11, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x24, 0x0a, 0x12, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x75, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescOnce sync.Once
	file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescData = file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDesc
)

func file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescGZIP() []byte {
	file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescOnce.Do(func() {
		file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescData)
	})
	return file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDescData
}

var file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_resources_alertpolicy_v1_alertpolicy_proto_goTypes = []interface{}{
	(*AlertPolicy)(nil),        // 0: pkg.resources.alertpolicy.v1.AlertPolicy
	(*AlertTarget)(nil),        // 1: pkg.resources.alertpolicy.v1.AlertTarget
	(*TargetMemberGroup)(nil),  // 2: pkg.resources.alertpolicy.v1.TargetMemberGroup
	(*TargetNotification)(nil), // 3: pkg.resources.alertpolicy.v1.TargetNotification
}
var file_pkg_resources_alertpolicy_v1_alertpolicy_proto_depIdxs = []int32{
	1, // 0: pkg.resources.alertpolicy.v1.AlertPolicy.alert_targets:type_name -> pkg.resources.alertpolicy.v1.AlertTarget
	3, // 1: pkg.resources.alertpolicy.v1.AlertTarget.notification:type_name -> pkg.resources.alertpolicy.v1.TargetNotification
	2, // 2: pkg.resources.alertpolicy.v1.AlertTarget.member_group:type_name -> pkg.resources.alertpolicy.v1.TargetMemberGroup
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_resources_alertpolicy_v1_alertpolicy_proto_init() }
func file_pkg_resources_alertpolicy_v1_alertpolicy_proto_init() {
	if File_pkg_resources_alertpolicy_v1_alertpolicy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetMemberGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_resources_alertpolicy_v1_alertpolicy_proto_goTypes,
		DependencyIndexes: file_pkg_resources_alertpolicy_v1_alertpolicy_proto_depIdxs,
		MessageInfos:      file_pkg_resources_alertpolicy_v1_alertpolicy_proto_msgTypes,
	}.Build()
	File_pkg_resources_alertpolicy_v1_alertpolicy_proto = out.File
	file_pkg_resources_alertpolicy_v1_alertpolicy_proto_rawDesc = nil
	file_pkg_resources_alertpolicy_v1_alertpolicy_proto_goTypes = nil
	file_pkg_resources_alertpolicy_v1_alertpolicy_proto_depIdxs = nil
}
