// Code generated by Iacker. DO NOT EDIT IT.
package v1

import (
	_ "embed"
)

// ResourceType is the unique type name of BlackList
const ResourceType = "BlackList"

//go:embed blacklist.schema.json
var schemaRaw []byte

const (
	// FilterOperationIn is the value of Equal
	FilterOperationIn = "in"
	// FilterOperationNotIn is the value of Not equal
	FilterOperationNotIn = "not in"
	// FilterOperationMatch is the value of Match
	FilterOperationMatch = "match"
	// FilterOperationNotMatch is the value of Not match
	FilterOperationNotMatch = "not match"
)

const (
	// SourceTypeLogging is the value of logging
	SourceTypeLogging = "logging"
	// SourceTypeObject is the value of object
	SourceTypeObject = "object"
	// SourceTypeCustomObject is the value of custom_object
	SourceTypeCustomObject = "custom_object"
	// SourceTypeNetwork is the value of network
	SourceTypeNetwork = "network"
	// SourceTypeTracing is the value of tracing
	SourceTypeTracing = "tracing"
	// SourceTypeRum is the value of RUM
	SourceTypeRum = "rum"
	// SourceTypeSecurity is the value of security
	SourceTypeSecurity = "security"
	// SourceTypeKeyevent is the value of keyevent
	SourceTypeKeyevent = "keyevent"
	// SourceTypeMetric is the value of metric
	SourceTypeMetric = "metric"
)

// resourceSchema is the schema of BlackList
type resourceSchema struct{}

// Raw returns the raw schema bytes of BlackList
func (s *resourceSchema) Raw() []byte {
	return schemaRaw
}

// ReferenceTypes returns the related resource types of BlackList
func (s *resourceSchema) ReferenceTypes() []string {
	return []string{}
}
