// Code generated by Iacker. DO NOT EDIT IT.
package v1

import (
	_ "embed"
)

// ResourceType is the unique type name of MemberGroup
const ResourceType = "MemberGroup"

//go:embed membergroup.schema.json
var schemaRaw []byte

// resourceSchema is the schema of MemberGroup
type resourceSchema struct{}

// Raw returns the raw schema bytes of MemberGroup
func (s *resourceSchema) Raw() []byte {
	return schemaRaw
}

// ReferenceTypes returns the related resource types of MemberGroup
func (s *resourceSchema) ReferenceTypes() []string {
	return []string{}
}
