// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pkg/notification/v1/notification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DingTalkRobot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DingTalk Robot Call Address
	Webhook string `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// DingTalk Robot Call Secret
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *DingTalkRobot) Reset() {
	*x = DingTalkRobot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_notification_v1_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DingTalkRobot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DingTalkRobot) ProtoMessage() {}

func (x *DingTalkRobot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_v1_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DingTalkRobot.ProtoReflect.Descriptor instead.
func (*DingTalkRobot) Descriptor() ([]byte, []int) {
	return file_pkg_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *DingTalkRobot) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

func (x *DingTalkRobot) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type FeishuRobot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Feishu Robot Call Address
	Webhook string `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// Feishu Robot Call Secret
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *FeishuRobot) Reset() {
	*x = FeishuRobot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_notification_v1_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeishuRobot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeishuRobot) ProtoMessage() {}

func (x *FeishuRobot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_v1_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeishuRobot.ProtoReflect.Descriptor instead.
func (*FeishuRobot) Descriptor() ([]byte, []int) {
	return file_pkg_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *FeishuRobot) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

func (x *FeishuRobot) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type HTTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// HTTP Call Address
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_notification_v1_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_v1_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_pkg_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MailGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Member Account List
	To []string `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
}

func (x *MailGroup) Reset() {
	*x = MailGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_notification_v1_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailGroup) ProtoMessage() {}

func (x *MailGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_v1_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailGroup.ProtoReflect.Descriptor instead.
func (*MailGroup) Descriptor() ([]byte, []int) {
	return file_pkg_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *MailGroup) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Notification object name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Trigger rule type
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// DingTalk Robot
	DingTalkRobot *DingTalkRobot `protobuf:"bytes,3,opt,name=ding_talk_robot,json=dingTalkRobot,proto3" json:"ding_talk_robot,omitempty"`
	// HTTP Request
	HttpRequest *HTTPRequest `protobuf:"bytes,4,opt,name=http_request,json=httpRequest,proto3" json:"http_request,omitempty"`
	// WeChat Robot
	WechatRobot *WeChatRobot `protobuf:"bytes,5,opt,name=wechat_robot,json=wechatRobot,proto3" json:"wechat_robot,omitempty"`
	// Mail Group
	MailGroup *MailGroup `protobuf:"bytes,6,opt,name=mail_group,json=mailGroup,proto3" json:"mail_group,omitempty"`
	// Feishu Robot
	FeishuRobot *FeishuRobot `protobuf:"bytes,7,opt,name=feishu_robot,json=feishuRobot,proto3" json:"feishu_robot,omitempty"`
	// SMS
	Sms *SMS `protobuf:"bytes,8,opt,name=sms,proto3" json:"sms,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_notification_v1_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_v1_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_pkg_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *Notification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetDingTalkRobot() *DingTalkRobot {
	if x != nil {
		return x.DingTalkRobot
	}
	return nil
}

func (x *Notification) GetHttpRequest() *HTTPRequest {
	if x != nil {
		return x.HttpRequest
	}
	return nil
}

func (x *Notification) GetWechatRobot() *WeChatRobot {
	if x != nil {
		return x.WechatRobot
	}
	return nil
}

func (x *Notification) GetMailGroup() *MailGroup {
	if x != nil {
		return x.MailGroup
	}
	return nil
}

func (x *Notification) GetFeishuRobot() *FeishuRobot {
	if x != nil {
		return x.FeishuRobot
	}
	return nil
}

func (x *Notification) GetSms() *SMS {
	if x != nil {
		return x.Sms
	}
	return nil
}

type SMS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Phone Number List
	To []string `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
}

func (x *SMS) Reset() {
	*x = SMS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_notification_v1_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMS) ProtoMessage() {}

func (x *SMS) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_v1_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMS.ProtoReflect.Descriptor instead.
func (*SMS) Descriptor() ([]byte, []int) {
	return file_pkg_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SMS) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

type WeChatRobot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Robot Call Address
	Webhook string `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
}

func (x *WeChatRobot) Reset() {
	*x = WeChatRobot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_notification_v1_notification_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeChatRobot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeChatRobot) ProtoMessage() {}

func (x *WeChatRobot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_notification_v1_notification_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeChatRobot.ProtoReflect.Descriptor instead.
func (*WeChatRobot) Descriptor() ([]byte, []int) {
	return file_pkg_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *WeChatRobot) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

var File_pkg_notification_v1_notification_proto protoreflect.FileDescriptor

var file_pkg_notification_v1_notification_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x41, 0x0a, 0x0d, 0x44, 0x69, 0x6e, 0x67, 0x54,
	0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x68,
	0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x3f, 0x0a, 0x0b, 0x46, 0x65,
	0x69, 0x73, 0x68, 0x75, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62, 0x68,
	0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x1f, 0x0a, 0x0b, 0x48,
	0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x1b, 0x0a, 0x09,
	0x4d, 0x61, 0x69, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0xf8, 0x03, 0x0a, 0x0c, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x6c, 0x6b, 0x5f,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x6b,
	0x67, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x6e, 0x67,
	0x54, 0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x0d, 0x64, 0x69, 0x6e, 0x67, 0x54,
	0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x4d, 0x0a, 0x0c, 0x68, 0x74, 0x74, 0x70,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x68, 0x74, 0x74, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x0c, 0x77, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x0b, 0x77, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x47, 0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x6b, 0x67,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x09, 0x6d, 0x61, 0x69, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x4d, 0x0a, 0x0c, 0x66, 0x65, 0x69, 0x73, 0x68, 0x75, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x69, 0x73, 0x68, 0x75, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x52, 0x0b, 0x66, 0x65, 0x69, 0x73, 0x68, 0x75, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x34,
	0x0a, 0x03, 0x73, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x6b,
	0x67, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x4d, 0x53, 0x52,
	0x03, 0x73, 0x6d, 0x73, 0x22, 0x15, 0x0a, 0x03, 0x53, 0x4d, 0x53, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x57,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x47, 0x75, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x6f,
	0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_notification_v1_notification_proto_rawDescOnce sync.Once
	file_pkg_notification_v1_notification_proto_rawDescData = file_pkg_notification_v1_notification_proto_rawDesc
)

func file_pkg_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_pkg_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_pkg_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_notification_v1_notification_proto_rawDescData)
	})
	return file_pkg_notification_v1_notification_proto_rawDescData
}

var file_pkg_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_notification_v1_notification_proto_goTypes = []interface{}{
	(*DingTalkRobot)(nil), // 0: pkg.resources.notification.v1.DingTalkRobot
	(*FeishuRobot)(nil),   // 1: pkg.resources.notification.v1.FeishuRobot
	(*HTTPRequest)(nil),   // 2: pkg.resources.notification.v1.HTTPRequest
	(*MailGroup)(nil),     // 3: pkg.resources.notification.v1.MailGroup
	(*Notification)(nil),  // 4: pkg.resources.notification.v1.Notification
	(*SMS)(nil),           // 5: pkg.resources.notification.v1.SMS
	(*WeChatRobot)(nil),   // 6: pkg.resources.notification.v1.WeChatRobot
}
var file_pkg_notification_v1_notification_proto_depIdxs = []int32{
	0, // 0: pkg.resources.notification.v1.Notification.ding_talk_robot:type_name -> pkg.resources.notification.v1.DingTalkRobot
	2, // 1: pkg.resources.notification.v1.Notification.http_request:type_name -> pkg.resources.notification.v1.HTTPRequest
	6, // 2: pkg.resources.notification.v1.Notification.wechat_robot:type_name -> pkg.resources.notification.v1.WeChatRobot
	3, // 3: pkg.resources.notification.v1.Notification.mail_group:type_name -> pkg.resources.notification.v1.MailGroup
	1, // 4: pkg.resources.notification.v1.Notification.feishu_robot:type_name -> pkg.resources.notification.v1.FeishuRobot
	5, // 5: pkg.resources.notification.v1.Notification.sms:type_name -> pkg.resources.notification.v1.SMS
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_notification_v1_notification_proto_init() }
func file_pkg_notification_v1_notification_proto_init() {
	if File_pkg_notification_v1_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_notification_v1_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DingTalkRobot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_notification_v1_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeishuRobot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_notification_v1_notification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_notification_v1_notification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_notification_v1_notification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_notification_v1_notification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_notification_v1_notification_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeChatRobot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_notification_v1_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_pkg_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_pkg_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_pkg_notification_v1_notification_proto = out.File
	file_pkg_notification_v1_notification_proto_rawDesc = nil
	file_pkg_notification_v1_notification_proto_goTypes = nil
	file_pkg_notification_v1_notification_proto_depIdxs = nil
}
