// Code generated by Iacker. DO NOT EDIT IT.
package v1

import (
	_ "embed"
)

// ResourceType is the unique type name of Dashboard
const ResourceType = "Dashboard"

//go:embed dashboard.schema.json
var schemaRaw []byte

// resourceSchema is the schema of Dashboard
type resourceSchema struct{}

// Raw returns the raw schema bytes of Dashboard
func (s *resourceSchema) Raw() []byte {
	return schemaRaw
}

// ReferenceTypes returns the related resource types of Dashboard
func (s *resourceSchema) ReferenceTypes() []string {
	return []string{}
}
